# Generated by Django 5.1.2 on 2024-10-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
