# Generated by Django 5.1.2 on 2024-10-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
