# Generated by Django 5.1.2 on 2024-10-16 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_records', '0002_medicalrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='notes',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.CharField(default='Not diagnosed', max_length=255),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lab_results',
            field=models.TextField(default='No lab results available'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='treatment_plan',
            field=models.TextField(default='No treatment plan specified'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records_as_doctor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records_as_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HealthRecord',
        ),
    ]
